### ISSUE TITLE
Loading Scenes

### ISSUE THREAD

**Issue by Beersteve** [bahamas10/hueadm#4]
Good evening

Thank you for this awesome utility.
Sadly i have issues loading scenes using your utility.
i tried loading a scene using:

hueadm scene 0iuextZLLkiIGi4

Here's the output:

name: W50B
lights:
    - '1'
    - '2'
    - '3'
    - '4'
owner: clSUBg97yuNhjXMn7qRe57azRi1qLygQaOZcEuZY
recycle: false
locked: true
appdata: {}
picture: ""
lastupdated: '2018-04-06T23:16:51'
version: 2
lightstates:
    '1': {on: true, bri: 126, ct: 500, transitiontime: 0}
    '2': {on: true, bri: 128, ct: 500, transitiontime: 0}
    '3': {on: true, bri: 128, ct: 500, transitiontime: 0}
    '4': {on: true, bri: 128, ct: 454, transitiontime: 0}

i'd be glad if you could point me in the right direction.
Thank you

Kind regards
Beersteve

**Comment by bahamas10** [comment]
So that output looks right to me... the `hueadm scene(s)` commands are just used to get/modify/delete scenes.... not "recall" (load) them.

See: https://developers.meethue.com/documentation/scenes-api#44_recall_scene

> To recall an existing scene you use the Groups API. Check out the Groups API set group state for details.

There is no builtin method with `hueadm` to do this (unfortunately! i'd welcome it) but you can do something like this:

```
$ echo '{"scene":"96AdAhdKe6vY99Z"}' | hueadm group 1
```

Hopefully this helps!

**Comment by Beersteve** [comment]
Thanks for the quick response.

I think i will find my way using the information from your response.
Thanks for pointing me in the right direction.
